### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by mschiff** [SaltyPaws/SAR_pi#2]
Hi!

It would be very usefull to have tagged releases, so the source for a specific version of th eplugin can be downloaded. Please add a release/tag for your released versions. This makes packaging a lot easier. 

I'd like to package this plugin for Gentoo Linux and for that it requires a reliable specific download URL for the releases. 

Thanks in advance!

**Comment by mschiff** [comment]
Ping? I really would like to add your plugin to Gentoo Linux but we need release tags for this. Could you please tag your OpenCPN plugins?

**Comment by mschiff** [comment]
Ping? Would really be great to have a source code release. Thanks...

**Comment by SaltyPaws** [comment]
Done, I thought I had done it long time ago. Thanks for the reminder. Let me know if you have any binaries to attach.
