### ISSUE TITLE
obsolete source : would you update it please

### ISSUE THREAD

**Issue by filochard** [SaltyPaws/SAR_pi#4]
Hi
I saw that you provide a version 1.0 for mac OSX and windows since june 2015
For linux we only have version 0.8 without the opencpn headers 
Your plugin doesn't build inside the last opencpn tree (4.0)
I discovered some pull requests allowing to build your plugin outside of the opencpn tree but they were not merged!

Do you use hidden or private sources to build your packages for Mac or Windows ?

**Comment by filochard** [comment]
PS 
I just could build with nohal's fork that is worth merging !

**Comment by SaltyPaws** [comment]
Nohal's build fixes have been implemented with his commit. Switch to the standard build system #3. This should close this issue.
