### ISSUE TITLE
Dangerous result needs fixing.

### ISSUE THREAD

**Issue by rgleason** [SaltyPaws/SAR_pi#5]
Dear Walter,

I hope we can get this fixed.

http://www.cruisersforum.com/forums/f134/saltypaws-plug-in-sar-90663.html

Conversion error due to user error, dangerous result
https://opencpn.org/flyspray/index.php?do=details&task_id=2110

As a result the download links to SAR_pi have been removed from the website because it is a hazard in an important safety plugin.

Can we get this fixed so we can add it back to the downloads page?

**Comment by SaltyPaws** [comment]
Ok, I will fix this bug.

**Comment by rgleason** [comment]
Thanks!

**Comment by rgleason** [comment]
Mike has fixed this and made some great improvements with the help of a Rescue Team SAR expert, with  many discussions about the practical aspects for use of this plugin in an emergency. Mike made adjustments to the interface in response to this discussion. Closing
