### ISSUE TITLE
Waypoints placement error with small distances

### ISSUE THREAD

**Issue by Kupofty** [SaltyPaws/SAR_pi#8]
Hi !

I want to use the SAR plugin to create a "SAR:trackline" route for SAR mission with a ROV.
I want (approximately) a leg distance of 5 meters (0.0027 NM) and a leg spacing of 10 meters (0.0054 NM).
But everytime I set a search leg length inferior to 0.1NM (185.2m) the leg length is equal to 1NM(1852m).
It seems to works fine for the track space length with distance of a few meters.
Is there a way to fix that ?
Thanks !

![image](https://github.com/SaltyPaws/SAR_pi/assets/69522980/0b3de6f0-d341-4d2a-819e-6f35cfeb770f)

PS : an option to directly input meters, kilometers,etc instead of NM would be a great feature because it is not easy to work with NM for small distances and it requires to do the conversion outside opencpn

**Comment by Kupofty** [comment]
Hi @SaltyPaws, @rgleason 
Any chance you are still working on this plugin ?
Do you have an idea where this problem might be coming from ?
Thanks

**Comment by rgleason** [comment]
Mike @Rasbats has it now, will respond.

**Comment by Kupofty** [comment]
See [Waypoints placement error with small distances - Rasbats](https://github.com/Rasbats/sar_pi/issues/7)

**Comment by Kupofty** [comment]
Hi @SaltyPaws , @rgleason ,

I was curious about the minimum leg length of 0.1NM in SAR routes and Rasbats advised me to ask you directly.
If you have some time to answer/discuss it, the discussion is here : https://github.com/Rasbats/sar_pi/discussions/12 :+1:
